JNG-4625 Judo ng project replacment
BlackBeltTechnology/judo-jsl-springboot-archetype pull request #39
Opened 2023-03-13 14:08 UTC by gaborflorian

JNG-4625 Judo ng project replacment

2023-03-17 13:57 UTC, noherczeg requested changes
Missing eof for:
./pom.xml
./.github/workflows/delete-old-draft-releases.yml

2023-03-21 12:20 UTC, bencegelei approved these changes

2023-03-21 16:15 UTC, noherczeg approved these changes

2023-03-22 21:38 UTC, bencegelei approved these changes

2023-03-22 21:39 UTC, bencegelei approved these changes

2023-03-24 13:50 UTC, merged